### ISSUE TITLE
Crashes at start with 'READ_PAIR_COUNT'

### ISSUE THREAD

**Issue by iamh2o** [DecodeGenetics/read_haps#1]
I am using a valid BAM file (many other tools are consuming it no problem).  My VCF is also seemingly valid.  Any thoughts on what might be going on here?

`$ ~/projects/other_tools/read_haps/bin/read_haps  GBA.aligned.deduped.sort.bam ~/projects/other_tools/read_haps/high_quality_markers_deCODE_2015.txt.gz ./GBA.octopus.vcf.gz -fa ~/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta
SNP_PAIRS ERROR_PAIRS DOUBLE_ERROR_PAIR_COUNT DOUBLE_ERROR_FRACTION REL_ERROR_FRACTION NONSENSE_FRACTION PASS_FAIL REASON
0 0 0 0 0 0 FAIL READ_PAIR_COUNT`

Thanks-
john major

**Comment by bjarnivh** [comment]
The program seems to run as expected.  The output is "FAIL" and the reason is "READ_PAIR_COUNT".  

It fails the sample as it does not find any read pairs that overlap the SNPs in the set of high quality markers.  It seems that you are using a GRCh37 fasta and presumably also a GRCh37 bam file.  The SNPs provided are however for GRCh38.  To run the tool for GRCh37 you would need to input a set of high quality SNPs for that assembly, which we have not provided.

**Comment by bjarnivh** [comment]
Another explanation might be that you are inputting the gz set of markers, the program assumes that the marker set is provided unzipped.
